on:
    push:
        branches:
            - main
        paths:
            - 'aquawatch_mobile_app/**'   
    workflow_dispatch: # Manual trigger
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 🏗 Setup repo
              uses: actions/checkout@v3

            - name: 🏗 Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x

            - name: 🏗 Setup EAS
              run: npm install eas-cli
            
            - name: Login to EAS
              env:
                EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
              run: eas login --token $EXPO_TOKEN

            - name: 📦 Install dependencies
              run: npm install

            - name: 🚀 Build app
              run: eas build -p android -profile production

